### ISSUE TITLE
Doesn't work with EKS via `heptio-authenticator-aws`

### ISSUE THREAD

**Issue by alexcouper** [dtan4/k8sec#30]
### Summary

I'm running on EKS using the `heptio-authentiator-aws` tool for authorization and it seems k8sec doesn't engage with that.

### Details
I'm using EKS and have this in my `.kube/config`:
```
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "<cluster_name>"
```

I can use `kubectl get secrets` and `create secret generic` from the command line, but when I use `k8sec`, I get:

```
Failed to retrieve secrets.: secrets "test-secret" is forbidden: User "system:anonymous" cannot get secrets in the namespace "default"
```
